### ISSUE TITLE
[Bug]: Whether to support intervene_on_prompt=False

### ISSUE THREAD

**Issue by jinzhuoran** [stanfordnlp/pyvene#150]
### What happened?

A bug happened! My understanding of `intervene_on_prompt=False` is that it involves adding an intervention vector even when generating new tokens. However, when I tried setting `intervene_on_prompt=False`, I encountered a RuntimeError:
`CUDA error: device-side assert triggered. CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging, consider passing CUDA_LAUNCH_BLOCKING=1. Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.`
Does this toolkit currently support `intervene_on_prompt=False`? Please correct me if I am wrong.

**Comment by frankaging** [comment]
Hey @jinzhuoran thx for your question!

Currently, if we set `intervene_on_prompt=True`, the `unit_locations` field has to be set to `0`, which means we are intervening on current decoding step, which is the 0th token (since transformer huggingface does the KV cache thing, all prompt reprs will be cached; and at each decoding step, there will be a batch of sequence with length = 1). Does this make sense?

**Comment by frankaging** [comment]
closing this issue for now --- feel free to reopen if there are more questions.
